[package]
name = "crypter"
version = "0.1.0"
edition = "2021"

[dependencies]
openssl = { version = "0.10.41", features = ["vendored"] }
paste = "1.0.7"
thiserror = "1.0.31"

[dev-dependencies]
anyhow = "1.0.58"
rand = "0.8.5"
